# Generated by Django 6.0.4 on 2026-06-08 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='pincode',
        ),
    ]
