# Generated by Django 6.0.4 on 2026-06-08 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
        ('jobseeker', '0002_remove_jobseeker_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='job.jobcategory'),
            preserve_default=False,
        ),
    ]
