# Generated by Django 6.0.4 on 2026-06-08 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_initial'),
        ('jobseeker', '0003_jobseeker_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobseeker',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobcategory'),
        ),
    ]
