# Generated by Django 6.0.4 on 2026-06-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_alter_jobseeker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseeker',
            name='objective',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
