# Generated by Django 6.0.4 on 2026-06-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_jobseeker_objective'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseeker',
            name='profile_photo',
        ),
    ]
