# Generated by Django 6.0.4 on 2026-06-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
