# Generated by Django 6.0.4 on 2026-06-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_payment_amount_remove_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.featuredplan'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
